<?php

echo $_SERVER['PHP_SELF'].' 		PHP_SELF';
echo "<br>";
echo $_SERVER['HTTP_USER_AGENT']. '		HTTP_USER_AGENT';
echo "<br>";
echo $_SERVER['GATEWAY_INTERFACE'].'		GATEWAY_INTERFACE';
echo "<br>";
echo $_SERVER['SERVER_ADDR'].'		SERVER_ADDR';
echo "<br>";
echo $_SERVER['SERVER_NAME'].'		SERVER_NAME';
echo "<br>";
echo $_SERVER['SERVER_SOFTWARE'].'		SERVER_SOFTWARE';
echo "<br>";
echo $_SERVER['SERVER_PROTOCOL'].'		SERVER_PROTOCOL';
echo "<br>";
echo $_SERVER['REQUEST_METHOD'].'		REQUEST_METHOD';
echo "<br>";
echo $_SERVER['REQUEST_TIME'].'			REQUEST_TIME';
echo "<br>";
echo $_SERVER['QUERY_STRING'].'			QUERY_STRING';
echo "<br>";
echo $_SERVER['HTTP_ACCEPT'].'			HTTP_ACCEPT';
echo "<br>";
echo $_SERVER['HTTP_ACCEPT_CHARSET'].'			HTTP_ACCEPT_CHARSET';//
echo "<br>";
echo $_SERVER['HTTP_HOST'].'		HTTP_HOST';
echo "<br>";
echo $_SERVER['HTTP_REFERER'].'			HTTP_REFERER';
echo "<br>";
echo $_SERVER['HTTPS'].'		HTTPS';
echo "<br>";
echo $_SERVER['REMOTE_ADDR'].'		REMOTE_ADDR';
echo "<br>";
echo $_SERVER['REMOTE_HOST'].'		REMOTE_HOST';
echo "<br>";
echo $_SERVER['REMOTE_PORT'].'		REMOTE_PORT';
echo "<br>";
echo $_SERVER['SCRIPT_FILENAME'].'		SCRIPT_FILENAME';
echo "<br>";
echo $_SERVER['SERVER_ADMIN'].'		SERVER_ADMIN';
echo "<br>";
echo $_SERVER['SERVER_PORT'].'		SERVER_PORT';
echo "<br>";
echo $_SERVER['SERVER_SIGNATURE'].'		SERVER_SIGNATURE';
echo "<br>";
echo $_SERVER['PATH_TRANSLATED'].'		PATH_TRANSLATED';
echo "<br>";
echo $_SERVER['SCRIPT_NAME'].'		SCRIPT_NAME';
echo "<br>";
echo$_SERVER['SCRIPT_URI'].'		SCRIPT_URI';
?>
